/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/apple_logo.glb --transform
Author: l o u i s (https://sketchfab.com/louis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-logo-8b13cb3155da41108b1a13e3bc35442d
Title: APPLE LOGO
*/

import React, { useLayoutEffect, useRef } from "react";
import { Center, useGLTF } from "@react-three/drei";

export default function AppleLogo(props) {
	const { centered, tl, ...otherProps } = props;

	const ref = useRef();

	useLayoutEffect(() => {
		ref.current.material.transparent = true;

		if (tl) {
			tl.to(
				ref.current.material,
				{
					opacity: 0,
					duration: 0.175,
					ease: "power0.in",
				},
				0,
			);
		}
	}, [tl]);

	const { nodes, materials } = useGLTF("/apple_logo-transformed.glb");
	return (
		<group {...otherProps} dispose={null}>
			{centered ? (
				<Center position={[-1, -9.5, 0]}>
					<mesh
						ref={ref}
						geometry={nodes.Object_2.geometry}
						material={materials["Scene_-_Root"]}
						scale={0.15}
						rotation-y={Math.PI}
					/>
				</Center>
			) : (
				<mesh
					ref={ref}
					geometry={nodes.Object_2.geometry}
					material={materials["Scene_-_Root"]}
					scale={0.25}
					rotation-y={Math.PI}
				/>
			)}
		</group>
	);
}

useGLTF.preload("/apple_logo-transformed.glb");
