/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/apple_logo.glb --transform
Author: l o u i s (https://sketchfab.com/louis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-logo-8b13cb3155da41108b1a13e3bc35442d
Title: APPLE LOGO
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AppleLogo(props) {
	const { nodes, materials } = useGLTF("/apple_logo-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_2.geometry}
				material={materials["Scene_-_Root"]}
			/>
		</group>
	);
}

useGLTF.preload("/apple_logo-transformed.glb");
